name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read tag
        id: tag
        run: |
          TAG=$(cat tag.txt)
          echo "::set-output name=tag::$TAG"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: csle-lab/protosim
          ref: "${{ steps.tag.outputs.tag }}"
          path: ./protosim
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Build
        run: |
          cd protosim
          yarn install
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./protosim/protosim
          publish_branch: pages
